# Generated by Django 3.1.3 on 2020-12-10 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointedteachers',
            fields=[
                ('appointed_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'db_table': 'appointedteachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numberclass', models.IntegerField(db_column='numberClass')),
                ('titleclass', models.CharField(db_column='titleClass', max_length=1)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daysweek',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nameday', models.CharField(blank=True, db_column='nameDay', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'db_table': 'daysweek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numberslesson',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Номер урока',
                'verbose_name_plural': 'Номера уроков',
                'db_table': 'numberslesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('visit', models.BooleanField(blank=True, default=True, null=True, verbose_name='Присутствовал/отсутствовал')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Записи журнала',
                'db_table': 'register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('datelesson', models.DateField(blank=True, db_column='dateLesson', null=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Расписание',
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('namesubject', models.CharField(db_column='NameSubject', max_length=32)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Useres',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.useres')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Schooler',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes', verbose_name='Класс')),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.useres')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'db_table': 'schooler',
            },
        ),
    ]
