# Generated by Django 3.1.3 on 2020-12-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
