# Generated by Django 3.1.3 on 2020-12-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullschedule',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('home_task', models.CharField(db_column='Task', max_length=255)),
                ('datelesson', models.DateField(blank=True, db_column='dateLesson', null=True)),
            ],
            options={
                'verbose_name': 'Заполненный урок',
                'verbose_name_plural': 'Заполненные уроки',
                'db_table': 'fullschedule',
                'managed': False,
            },
        ),
    ]
